More tuning

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -61,11 +61,6 @@ jobs:
           docker run --rm \
             roboplan_ubuntu:${{ steps.sanitize_tag.outputs.tag }} \
             /bin/bash -c './scripts/run_tests.bash'
-      - name: Check bindings stub files
-        run: |
-          docker run --rm -v ./:/roboplan_ws/ \
-            roboplan_ubuntu:${{ steps.sanitize_tag.outputs.tag }} \
-            /bin/bash -c 'git config --global --add safe.directory /roboplan_ws && ./scripts/check_bindings_stubs.bash'
 
   # Build ROS docker images and run tests.
   ros_build_and_test:
@@ -139,10 +134,19 @@ jobs:
           manifest-path: pixi.toml
       - name: Build and test
         run: |
-          pixi run install_all
-          pixi run build_tests
-          pixi run test_all
+          pixi run -e ci install_all
+          pixi run -e ci build_tests
+          pixi run -e ci test_all
+      - name: Check bindings stub files
+        run: |
+          if ! git diff --exit-code --shortstat -- 'bindings/src/roboplan/roboplan_ext/*.pyi'; then
+            echo "::error::The .pyi stub files are out of sync with the source code. Make sure to rebuild the Python bindings without symlink builds and commit the changes."
+            echo "Git Diff:"
+            git diff -- 'bindings/src/roboplan/roboplan_ext/*.pyi'
+            exit 1
+          fi
+          echo "✅ .pyi stub files look good!"
       # TODO: Decide on a method for automated benchmark performance testing.
       - name: Run benchmarks
         run: |
-          pixi run test_benchmarks
+          pixi run -e ci test_benchmarks
